In [1]:
#Question-1

ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]   # List of 10 Student Ages
print(ages)                                      # ages list’s printing
ages.sort()                                     # Student ages sorting
print(ages)                              # Sorted student ages list printing
s = min(ages)                      # Obtaining the minimum age and putting it in Variable A
p = max(ages)                         # Obtaining and storing the minimum age in variable b
print(s)                                         # displaying the value contained in the variable a
print(p)                                       # displaying the value contained in the variable b
ages.append(s)                                            # The min value has been added to the list.
print(ages)                                            # ages list printing
ages.append(p)                                           # include the maximum value
print(ages)                                                     # ages list printing
q = len(ages)                                                 # calculating the list's length
print(q)                                                      # the length is being printed
u = (q-1)//2                                                    # floor division finding
print(u)                                                          # displaying d's value
med = (ages[u] + ages[u+1])/2                    # calculating the median
print(med)                                                      # the median value printed
sum = sum(ages)                                                # calculating the age total
print(sum)                                                           # printing the age total
avg = sum/q                                                        # calculating the mean
print(avg)                                                               # displaying the median
range = p-s                                                        # Calculating the range
print(range)                                                       # the range is printed



[19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
19
26
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 19]
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 19, 26]
12
5
24.0
273
22.75
7


In [2]:
#Question 2
dog={}
dog['name']= 'Rocky'
dog['color']= 'brown'
dog['breed']= 'German Shepherd'
dog['legs']=4
dog['age']=5

person=dict()
person['first_name']='Shameer'
person['last_name']= 'Shaik'
person['gender']='Male'
person['age']=24
person['Marital_status']='No'
person['skills']=['C','Python']
person['country']='India'
person['city']='Vijayawada'
person['address']= 'Vijayawada Local'

print(person)
print(len(person))
skills_of_person= person.get('skills')
print(person.get('skills'))
print(type(skills_of_person))
person.update({'skills':['C','Java','Python','Pyspark','Angular']})
print(person)
person_keys= list(person.keys())
print(person_keys)
person_values= list(person.values())
print(person_values)


{'first_name': 'Shameer', 'last_name': 'Shaik', 'gender': 'Male', 'age': 24, 'Marital_status': 'No', 'skills': ['C', 'Python'], 'country': 'India', 'city': 'Vijayawada', 'address': 'Vijayawada Local'}
9
['C', 'Python']
<class 'list'>
{'first_name': 'Shameer', 'last_name': 'Shaik', 'gender': 'Male', 'age': 24, 'Marital_status': 'No', 'skills': ['C', 'Java', 'Python', 'Pyspark', 'Angular'], 'country': 'India', 'city': 'Vijayawada', 'address': 'Vijayawada Local'}
['first_name', 'last_name', 'gender', 'age', 'Marital_status', 'skills', 'country', 'city', 'address']
['Shameer', 'Shaik', 'Male', 24, 'No', ['C', 'Java', 'Python', 'Pyspark', 'Angular'], 'India', 'Vijayawada', 'Vijayawada Local']


In [3]:
#Question 3

sis=('akhila','alekya','Priya')
bros=('gopi','rahul','revanth')
sib= sis+ bros
print(sib)
sib_count=len(sib)
print(sib_count)
temp_sib=list(sib)
temp_sib.extend(['sam','suresh'])
fam_mem=tuple(temp_sib)
print(fam_mem)


('akhila', 'alekya', 'Priya', 'gopi', 'rahul', 'revanth')
6
('akhila', 'alekya', 'Priya', 'gopi', 'rahul', 'revanth', 'sam', 'suresh')


In [4]:
#Question 4

it_comp = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
len_of_it=len(it_comp)
it_comp.add('Twitter')
print(it_comp)
it_comp.update({'Deloitte','Value Labs','HSBC'})
print(it_comp)
it_comp.remove('Microsoft')
print(it_comp)
# When an element that is not part of the set is removed using the remove method, an error is raised. Discard, however, will not raise an error even if no element is present.
A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}


C=A.union(B)
print(C)
A_inter_B= A.intersection(B)
print(A_inter_B)
subset_check= A.issubset(B)
print(subset_check)

disjoint_check= A.isdisjoint(B)
print(disjoint_check)
E=A.union(B)
D= B.union(A)
print(E)
print(D)

del A 
del B
del C
del D
del E
age = [22, 19, 24, 25, 26, 24, 25, 24]
len_age=len(age)
age_set=set(age)
len_age_set=len(age_set)
diff_age= len_age-len_age_set
print(diff_age)


{'Microsoft', 'IBM', 'Oracle', 'Amazon', 'Google', 'Twitter', 'Facebook', 'Apple'}
{'Microsoft', 'Oracle', 'Amazon', 'Google', 'Twitter', 'Facebook', 'Apple', 'HSBC', 'Value Labs', 'Deloitte', 'IBM'}
{'Oracle', 'Amazon', 'Google', 'Twitter', 'Facebook', 'Apple', 'HSBC', 'Value Labs', 'Deloitte', 'IBM'}
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26}
True
False
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26, 27, 28}
3


In [5]:
#Question 5


from math import pi                                                     # Pi import from the math module

r = 30                                                                       # Given radius = 30

area_of_circle = pi*r**2                                                    # calculating the circle's area

print("Area of circle the with radius 30 is " + str(area_of_circle))  
 # printing the circle's area

circum_of_circle = 2*pi*r                                            
    # calculating the circle's circumference

print("Circumference of circle the with radius 30 is " + str(circum_of_circle))   
  # Printing the circle's circumference


radius = float(input("Enter the radius of circle"))      
 # Using the user's input for the radius


area_of_circle_new_radius = pi*radius**2                
  # calculating the circle's area using the user's entered radius

print("Area of circle the with radius "+str(radius) + " is " + str(area_of_circle_new_radius))
 # printing the circle's area




Area of circle the with radius 30 is 2827.4333882308138
Circumference of circle the with radius 30 is 188.49555921538757
Enter the radius of circle5
Area of circle the with radius 5.0 is 78.53981633974483


In [6]:
#Question 6

line="I am a teacher and I love to inspire and teach people"
word_line=line.split(' ')
print(len(word_line))
uniq_words= set(word_line)
uniq_words=list(uniq_words)
print(len(uniq_words))


12
10


In [7]:
#Question 7

print('Name   \tAge\tCountry\tCity')
print('Asabeneh  250\tFinland\tHelsinki')


Name   	Age	Country	City
Asabeneh  250	Finland	Helsinki


In [8]:
#Question 8
r = 10
a = 3.14 * r ** 2

print('The area of a circle is', a)

The area of a circle is 314.0


In [9]:
#Question 9

#students weights list
weight_lbs = [150, 155, 145, 148]
weight_kgs = []

#weight to kg conversion
for x in weight_lbs:         # for loop
    weight_kgs.append(x*0.453592)    #values appending
weight_kgs=[round(x,2) for x in weight_kgs]
print("weight in kgs : ",weight_kgs)


weight in kgs :  [68.04, 70.31, 65.77, 67.13]


In [10]:
#Question 10


import numpy 			 #Bringing in the required libraries 
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from collections import Counter
import numpy as np
from sklearn.linear_model import LogisticRegression
a = np.array([1,2,3,6,6,7,10,11])            #constructing arrays
y = np.array([0,0,1,1,1,0,0,0])
x_train,x_test,y_train,y_test=train_test_split(a,y,test_size=0.5,random_state=4,stratify = y)
x_train = x_train.reshape(-1,1)
x_test = x_test.reshape(-1,1)
y_train = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)
print(x_train,x_test,y_train,y_test)
def KNNAlgo(a,b,k,d):
    dist = []                                 
    #The Euclidean distance calculation
    dist_ind = np.sqrt(np.sum((a-b)**2, axis=1))
    print(dist_ind)
    #combining the distance and the output label
    main_arr = np.column_stack((d,dist_ind))
    print(main_arr)
    #Distances are arranged in descending order.
    main = main_arr[main_arr[:,1].argsort()]
    #Based on the value of k, calculating the frequency of the labels
    count = Counter(main[0:k,0])
    keys, vals = list(count.keys()), list(count.values())
    if len(vals)>1:
        if vals[0]>vals[1]:
            return int(keys[0])
        else:
            return int(keys[1])
    else:
        return int(keys[0])

k=3
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(x_train,y_train)
ypred = knn.predict(x_test) 
for i in x_test:                                      #estimating the results' values
    result = KNNAlgo(x_train,i,3,y_train)
    print(result)
print(y_test,ypred)

A = confusion_matrix(y_test, y_test_pred)
print(A)
from sklearn.metrics import accuracy_score, confusion_matrix
confusion_matrix(y_test, ypred)
accuracy_score(y_test,ypred)                 #determining the precision
A = confusion_matrix(y_test, ypred)
print(A)
sensitivity = (A[1][1])/(A[1][1] + A[1][0])           #figuring out the sensitivity
print(sensitivity)            
specificity = (A[0][0])/(A[0][0]+A[0][1])          #Making a Specificity Calculation
print(specificity)

[[ 6]
 [ 3]
 [ 7]
 [11]] [[ 2]
 [10]
 [ 1]
 [ 6]] [[1]
 [1]
 [0]
 [0]] [[0]
 [0]
 [0]
 [1]]
[4. 1. 5. 9.]
[[1. 4.]
 [1. 1.]
 [0. 5.]
 [0. 9.]]
1
[4. 7. 3. 1.]
[[1. 4.]
 [1. 7.]
 [0. 3.]
 [0. 1.]]
0
[ 5.  2.  6. 10.]
[[ 1.  5.]
 [ 1.  2.]
 [ 0.  6.]
 [ 0. 10.]]
1
[0. 3. 1. 5.]
[[1. 0.]
 [1. 3.]
 [0. 1.]
 [0. 5.]]
1
[[0]
 [0]
 [0]
 [1]] [1 0 1 1]


C:\Users\91898\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


NameError: name 'confusion_matrix' is not defined